name: Deploy to Somee

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código usando git clone
      - name: Checkout code
        run: |
          git clone https://github.com/barckstar/GItHubDataFetch.git .
          git checkout main

      # Paso 2: Instalar .NET manualmente
      - name: Install .NET
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version 6.0.x

      # Paso 3: Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # Paso 4: Compilar el proyecto
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Paso 5: Publicar el proyecto
      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      # Paso 6: Desplegar a Somee usando lftp
      - name: Deploy to Somee
        run: |
          lftp -e "
            set ftp:ssl-allow no;
            open ${{ secrets.SOMEE_FTP_HOST }};
            user ${{ secrets.SOMEE_FTP_USERNAME }} ${{ secrets.SOMEE_FTP_PASSWORD }};
            mirror --reverse --delete ./publish /;
            quit;
          "
